<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSeEqBy3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSeEqBy3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSeEqBy3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSeEqBy3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSeEqBy3\App_KernelDevDebugContainer([
    'container.build_hash' => 'SeEqBy3',
    'container.build_id' => '37519b38',
    'container.build_time' => 1646405564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSeEqBy3');
